server/realtor/urls.py
from django.urls import path
from . import views
from user import views as user_views
from django.contrib.auth import views as auth_views


app_name = 'realtor'
urlpatterns = [
    path('', views.index, name='index'),  # URL for the index view 

    path('about', views.about, name='about'), 
    path('properties', views.property_detail, name='property-detail'),  # URL for property detail view
    path('agent', views.agent, name='agent' ),
    path('sign-up', user_views.sign_up, name='sign-up'),
    path('sign-in', user_views.sign_in, name='sign-in'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logout_view, name='logout'),
    path('upload-apartment', views.upload_apartment, name='upload-apartment'),
    path('view-properties', views.view_property, name='view-properties'),
     path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('realtor.urls')),
    path('user', include('user.urls')),
    # Include the URLs from the realtor app
    # You can add more includes here for other apps
]

server/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('sign-up', views.sign_up, name='sign-up'),
    path('sign-in', views.sign_in, name='sign-in'),
]

server/realtor/models.py
from django.db import models
from user.models import UserDetails

class Property(models.Model):
    agent = models.ForeignKey(UserDetails, on_delete=models.CASCADE, related_name='apartment')
    title = models.CharField(max_length=200)
    description = models.TextField()
    apartment_type = models.CharField(max_length=100, choices=[
        ('studio', 'Studio'),
        ('1_bedroom', '1 Bedroom'),
        ('2_bedroom', '2 Bedroom'),
        ('3_bedroom', '3 Bedroom'),
        ('4_bedroom', '4 Bedroom'),
        ('5_bedroom', '5 Bedroom'),
        ('duplex', 'Duplex'),
        ('penthouse', 'Penthouse'),
        ('villa', 'Villa'),
        ('townhouse', 'Townhouse'),
        ('condo', 'Condo'),
        ('cottage', 'Cottage'),
        ('bungalow', 'Bungalow'),
        ('loft', 'Loft'),
        ('other', 'Other')
    ])
    price = models.DecimalField(max_digits=12, decimal_places=2)
    image1 = models.ImageField(upload_to='image/')
    image2 = models.ImageField(upload_to='image/')
    image3 = models.ImageField(upload_to='image/')
    video_file = models.FileField(upload_to='property_videos')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    duration = models.PositiveIntegerField('text_duration in seconds')
    property_address = models.CharField(max_length=255)
    

    def __str__(self):
        return f'{self.title} by {self.agent.username}' 

server/realtor/forms.py
from django import forms
from django.core.validators import RegexValidator

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder':"Enter Your Name",'id':"name"}), required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Enter Your Email','id':"name"}), required=True)
    message = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'placeholder':'Enter Your Message'}), required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if not email.endswith('@example.com'):
            
            raise forms.ValidationError("Email must be from the domain 'example.com'")
        return email
    

class Apartment_upload(forms.Form):
    pass

server/realtor/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import forms
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index (request):
    """
    Render the index page for the realtor app.
    """
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('realtor:property-detail'))
    return render(request, 'index.html',{
        'forms': forms.ContactForm(),
        'user': request.user.is_authenticated
    })


def about(request):
    return render(request, 'about.html')

@login_required
def property_detail(request):
    """
    Render the property detail page for a specific property.
    """
    # Logic to retrieve property details by id would go here
    return render(request, 'properties.html')

@login_required
def upload_apartment(request):
    if request.method == 'POST':
        apartment = ""    
    return render(request, 'upload-apartment.html')

@login_required
def agent(request):
    return render(request, 'agents.html')

@login_required
def profile(request):
    return render(request, 'profile.html')

@login_required
def view_property(request):
    
    return render (request, 'view_properties.html')  

  
def logout_view(request):
    logout(request)
    return render(request, 'index.html',{
        'message':'logout'
    })

server/realtor/templates/pages/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Realtor - Home </title>
    {% endblock title %}
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}" >
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/solid.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css>
</head>
<body>
    
<!-- ----------------------Header----------------------- -->
<header>

        
        <div class="header-main-con container-1">


            <a href="{% url 'realtor:index' %}">
                <h1>AgentHub</h1>
            </a>


            <ul id="menu" class="menu">
                <li>
                    {% if request.user.is_authenticated %}
                             <a href="{% url 'realtor:property-detail' %}">Properties</a>
                      {% else %}
                    <a href="{% url 'user:sign-in' %}">Properties</a>
                {% endif %}
               </li>
                
               <li>
                {% if  request.user.is_authenticated %}
                 <a href="{% url 'realtor:agent' %}">Agent</a>
                {% else %}
                 <a href="{% url 'user:sign-in' %}">Agent</a>
                {% endif %}

               </li>
                    
            <li>
               <a href="{% url 'realtor:about' %}#service">Service</a>
            </li>

            <li>
                   <a href="{% url 'realtor:about' %}">About</a>
            </li>

                
               <div class="menu-2">
    {% if not request.user.is_authenticated %}
        <li><div class="div22"><a href="{% url 'user:sign-in' %}">Login</a></div></li>
        <li><div class="div33"><a href="{% url 'user:sign-up' %}">Join as agent</a></div></li>
    {% else %}
        <li><div class="div33 div34"><a href="{% url 'realtor:profile' %}">
            <i class="uil uil-user"></i>
        </a></div></li>
        <!-- Or include logout -->
        <li>
            <div class="div33">
                <a href="{% url 'realtor:logout' %}">
                    Logout
                </a></div></li>
    {% endif %}
</div>

            </ul>


            <label id="menu-toggle" class="menu-toggle">
                <i class="uil uil-bars icon visible" id="open-icon"></i>
                <i class="uil uil-times icon" id="close-icon"></i>
            </label>


        </div>

</header>

<div id="header-nav" class="header-nav"></div>
{% block body %}

{% endblock body %} 
<!-- ------------------------------- footer ------------------------------------ -->

<footer>
    <div class="footer-main-con container-1">

        <div class="footer-con">
            <h4>For Buyers</h4>
            <a href="">Browse Properties</a>
            <a href="">Find Agents</a>
            <a href="">Buying Guide</a>
        </div>



        <div class="footer-con">
            <h4>For Agents</h4>
            <a href="">Join Platform</a>
            <a href="">Agent Dashboard</a>
            <a href="">Marketing Tools</a>
            <a href="">Commission Info</a>
        </div>



        <div class="footer-con">
            <h4>Company</h4>
            <a href="">About Us</a>
            <a href="">How It Works</a>
            <a href="">Success Stories</a>
            <a href="">Press</a>
        </div>



        <div class="footer-con">
            <h4>Support</h4>
            <a href="{% url 'realtor:index' %}#contact">Contact Support</a>
            <a href="">FAQ</a>
            <a href="">Terms of Service</a>
            <a href="">Privacy Policy</a>
        </div>

    </div>


    <div class="c-r">
        <p>&copy; 2024 Property Hub. All rights reserved.</p>
    </div>


</footer>

<script src="{% static 'JS/main.js' %}"></script> 
</body>
</html>